language: go

env:
   global:
   -REPO=builds

install:
  make

script:
  make test
  make build

before_deploy:
  - cd ..
  - tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ${REPO}

deploy:
  # GitHub - Add zip to release
  - provider: releases
    api_key:
      secure: "7e45f03084a41bff5f7ffb1237df13bdf20463d4"
    file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
    skip_cleanup: true
    on:
      tags: true

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always