language: go

before_install:
  apt-get -y install zip

install:
  make

script:
  make test
  make build

before_deploy:
  if ! [[ $TRAVIS_TAG ]]; then
    export TRAVIS_TAG="1.$TRAVIS_BUILD_NUMBER" &&
    git config --local user.name "$USER_NAME" &&
    git config --local user.email "$USER_EMAIL" &&
    git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT";
  fi
  echo $TRAVIS_TAG

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always